### Merge
### The `merge` function is used to combine two or more dataframes based on a common column(s)

In [4]:
import pandas as pd

In [5]:
df_5 = pd.DataFrame({'Names': ['Ama', 'Barry', 'Celestine', 'Dela'], 'Score1': [1, 2, 3, 4]})
df_6 = pd.DataFrame({'Names': ['Barry', 'Dela', 'Emma', 'Frank'], 'Score2': [5, 6, 7, 8]})

In [10]:
pd.merge(df_5,df_6, on="Names" , how="inner") #inner Keeps only rows that match in both DataFrames.

   Names  Score1  Score2
0  Barry       2       5
1   Dela       4       6

In [9]:
pd.merge(df_5,df_6 , on="Names", how="outer") # outer Keeps ALL rows from both DataFrames.

       Names  Score1  Score2
0        Ama     1.0     NaN
1      Barry     2.0     5.0
2  Celestine     3.0     NaN
3       Dela     4.0     6.0
4       Emma     NaN     7.0
5      Frank     NaN     8.0

In [11]:
pd.merge(df_5, df_6, on='Names', how='left')

       Names  Score1  Score2
0        Ama       1     NaN
1      Barry       2     5.0
2  Celestine       3     NaN
3       Dela       4     6.0

In [12]:
pd.merge(df_5, df_6, on='Names', how='right')

   Names  Score1  Score2
0  Barry     2.0       5
1   Dela     4.0       6
2   Emma     NaN       7
3  Frank     NaN       8

In [13]:
# The two dataframeshaving differnt column names
df_7 = pd.DataFrame({'Name1': ['Ama', 'Barry', 'Celestine', 'Dela'], 'Score': [1, 2, 3, 4]})
df_8 = pd.DataFrame({'Name2': ['Barry', 'Dela', 'Emma', 'Frank'], 'Score': [5, 6, 7, 8]})
merged_df = pd.merge(df_7, df_8, left_on='Name1', right_on='Name2', how='inner', suffixes=('_df7', '_df8'))
merged_df

   Name1  Score_df7  Name2  Score_df8
0  Barry          2  Barry          5
1   Dela          4   Dela          6

In [14]:
df_7.merge(df_8,left_on='Name1', right_on='Name2', how='inner', suffixes=('_df7', '_df8'))

   Name1  Score_df7  Name2  Score_df8
0  Barry          2  Barry          5
1   Dela          4   Dela          6

###  Join
### The `join()` function id used to combine two dataframes on their indexes

In [15]:
df_9 = pd.DataFrame({'value1': [1, 2, 3, 4]}, index=['A', 'B', 'C', 'D'])
df_10 = pd.DataFrame({'value2': [5, 6, 7, 8]}, index=['B', 'D', 'E', 'F'])

In [16]:
df_9.join(df_10, how="inner")

   value1  value2
B       2       5
D       4       6

In [17]:
joined =df_9.join(df_10, how='left', lsuffix='_left', rsuffix='_right')
joined

   value1  value2
A       1     NaN
B       2     5.0
C       3     NaN
D       4     6.0

## Filtering: You can filter data based on conditions.

In [19]:
x = {'Name':["Harriet", "Rashid", "Olalode"],
     'Age': [30, 25, 35],
     'City': ['New York', 'Paris', 'London']}

In [20]:
df = pd.DataFrame(x)
df

      Name  Age      City
0  Harriet   30  New York
1   Rashid   25     Paris
2  Olalode   35    London

In [22]:
# Filtering rows based on condition
filtered_df = df[df['Age'] >30]
print(filtered_df)

      Name  Age    City
2  Olalode   35  London

## Adding and Removing Columns:
#### You can add new columns or remove existing ones.

In [23]:
#Code Example:
# Creating a DataFrame from a dictionary
data = {'Name': ['John', 'Alice', 'Bob'],
        'Age': [30, 25, 35],
        'City': ['New York', 'Paris', 'London']}
df = pd.DataFrame(data)
print(df)

    Name  Age      City
0   John   30  New York
1  Alice   25     Paris
2    Bob   35    London

In [24]:
# Adding a new column
df['Gender'] = ['Male', 'Female', 'Male']

print(df)

    Name  Age      City  Gender
0   John   30  New York    Male
1  Alice   25     Paris  Female
2    Bob   35    London    Male

In [25]:
# Removing a column
df.drop('City', axis=1, inplace=True)
df

    Name  Age  Gender
0   John   30    Male
1  Alice   25  Female
2    Bob   35    Male

## Grouping and Aggregation:
#### You can group data based on one or more columns and perform aggregation functions.

In [5]:
# Creating a DataFrame from a dictionary
data = {'Num': [10, 20, 30],
        'Age': [30, 25, 35],
        'val': [50, 60, 70]}
df = pd.DataFrame(data)
print(df)

   Num  Age  val
0   10   30   50
1   20   25   60
2   30   35   70

In [27]:
# Grouping and aggregating
grouped_df = df.groupby('Age').mean()
grouped_df

      Num   val
Age
25   20.0  60.0
30   10.0  50.0
35   30.0  70.0

In [6]:
grouped_df = df.groupby('Age').max()
grouped_df

     Num  val
Age
25    20   60
30    10   50
35    30   70

In [28]:
data = {'Num': [10, 20, 10, 20, 20, 30, 30],
        'Age': [30, 30, 25, 25, 25, 25, 35],
        'val': [50, 52, 64, 20, 50, 60, 70]}
dff = pd.DataFrame(data)
print(dff)

   Num  Age  val
0   10   30   50
1   20   30   52
2   10   25   64
3   20   25   20
4   20   25   50
5   30   25   60
6   30   35   70

In [29]:
grouped_dff = dff.groupby('Age').mean()
grouped_dff

      Num   val
Age
25   20.0  48.5
30   15.0  51.0
35   30.0  70.0

In [30]:
grouped_dff = dff.groupby('Age').max()
grouped_dff

     Num  val
Age
25    30   64
30    20   52
35    30   70

### Handling Missing Data:
#### Pandas provides methods for handling missing data, such as dropping or filling missing values.



#Dropping rows with missing values

#### cleaned_df = df.dropna()


#Filling missing values with a specified value

#### filled_df = df.fillna(0)

In [10]:
# Creating a DataFrame from a dictionary
data = {'A': [1, 2, None,4],
        'B': [None, 5, 6,7]}
df = pd.DataFrame(data)
df

     A    B
0  1.0  NaN
1  2.0  5.0
2  NaN  6.0
3  4.0  7.0

In [11]:
#check for missing values
print(df.isnull())

       A      B
0  False   True
1  False  False
2   True  False
3  False  False

In [14]:
# Drop Missing Values (dropna())
cleaned_df = df.dropna()
print(cleaned_df)                 # Rows 0 and 2 were removed because they had NaN.

     A    B
1  2.0  5.0
3  4.0  7.0

In [22]:
import pandas as pd

# Create DataFrame
data = {'A': [1, 2, None, 4],
        'B': [None, 5, 6, 7]}

df = pd.DataFrame(data)

# Fill missing values
filled_df = df.fillna(0)

print(filled_df)

     A    B
0  1.0  0.0
1  2.0  5.0
2  0.0  6.0
3  4.0  7.0

### Reading Files with Pandas:

#### Syntax
#### df = pd.read_csv('filename.csv')

### Options:
#### sep: Specifies the delimiter (default is ,).
#### header: Specifies the row number to use as column names.
#### index_col: Specifies the column to use as the row index.
#### usecols: Specifies a subset of columns to read.

In [23]:
import pandas as pd

# Reading CSV file with a different delimiter
df1 = pd.read_csv('sample_data.csv', sep=',')
print(df1.head())  # Displaying the first few rows of the DataFrame

    Name  Age           City
0   John   30       New York
1  Alice   25    Los Angeles
2    Bob   35        Chicago
3  Emily   28        Houston
4  David   32  San Francisco

In [35]:
import pandas as pd

# Read Excel file
df = pd.read_excel('sample_data_excel.xlsx')  

# Show first 5 rows
print(df.head())

    Name  Age           City
0   John   30       New York
1  Alice   25    Los Angeles
2    Bob   35        Chicago
3  Emily   28        Houston
4  David   32  San Francisco

In [37]:
print(df.tail())

       Name  Age          City
25    Henry   30  Indianapolis
26   Evelyn   35       Raleigh
27  Jackson   27      Columbus
28     Liam   33     Milwaukee
29  Abigail   26        Tucson