## Lambda Functions:

#### Lambda functions, also known as anonymous functions, are small, single-expression functions that can be defined inline using the lambda keyword.
### They are useful for creating quick, throwaway functions without the need for a formal def statement.

In [52]:
# Adding the numbers
add = lambda x, y: x + y
print(add(9, 5))

14

In [53]:
students = [
    {'name': 'Natalie','score':87},
    {'name':'Zacharia','score':90}
]
sorted_students = sorted(students,key=lambda x: x['score']) # automatically sorts in ascending order
print(sorted_students)

[{'name': 'Natalie', 'score': 87}, {'name': 'Zacharia', 'score': 90}]

In [54]:
students = [
    {'name': 'Natalie','score':87},
    {'name':'Zacharia','score':90}
]
sorted_students = sorted(students,key=lambda x: x['score'], reverse=True) # sorts in descending order
print(sorted_students)

[{'name': 'Zacharia', 'score': 90}, {'name': 'Natalie', 'score': 87}]

## Built-in Functions:

#### Python comes with several built-in functions that perform common operations efficiently.
#### Here's an overview of some commonly used ones:

### map(function, iterable):

#### Applies the given function to each item in the iterable and returns a new iterable with the results.

In [55]:
#Finding the square of the numbers in the list
numbers = [1, 2, 3, 4, 5]
squared = map(lambda x: x**2, numbers)
print(list(squared))

[1, 4, 9, 16, 25]

In [56]:
#Converting temperatures from Celsius to Fahrenheit using map:
temps_celsius = [0, 10, 20, 30, 40]
temps_fahrenheit = map(lambda c: (c * 9/5) + 32, temps_celsius)
print(list(temps_fahrenheit))

[32.0, 50.0, 68.0, 86.0, 104.0]

In [57]:
#Capitalizing the first letter of each word in a list of strings using map:
words = ["hello", "world", "python"]
capitalized_words = map(lambda w: w.capitalize(), words)
print(list(capitalized_words))

['Hello', 'World', 'Python']

### filter(function, iterable):

#### Filters elements from an iterable based on the given function's truthiness.

In [58]:
#Finding the even numbers in the list
numbers = [1, 2, 3, 4, 5]
evens = filter(lambda x: x % 2 == 0, numbers)
print(list(evens))

[2, 4]

In [59]:
#Filtering out negative numbers from a list:
numbers = [-2, 5, -7, 3, -1, 8]
positive_numbers = filter(lambda x: x >= 0, numbers)
print(list(positive_numbers))

[5, 3, 8]

In [60]:
# Filtering out even numbers from a list:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_numbers = filter(lambda x: x % 2 == 0, numbers)
print(list(even_numbers))

[2, 4, 6, 8, 10]

### reduce(function, iterable[, initializer]):

#### Applies the given function cumulatively to the items of the iterable, from left to right,
#### to reduce the iterable to a single value.

In [61]:
#Finding the product of the elements in the list
from functools import reduce
numbers = [1, 2, 3, 4, 5]
product = reduce(lambda x, y: x * y, numbers)
print(product)

120

In [62]:
#Finding the maximum element in a list using reduce:
numbers = [3, 8, 1, 6, 5]
max_num = reduce(lambda x, y: x if x > y else y, numbers)
print(max_num)

8

### sum(iterable[, start]):

#### Returns the sum of all elements in the iterable.

In [63]:
#find the sum of the numbers in the list
numbers = [1, 2, 3, 4, 5]
total = sum(numbers)
print(total)

15

### max(iterable[, key, default]):

#### Returns the maximum element from the iterable.

In [64]:
#Finding the maximum value in a list
numbers = [1, 2, 3, 4, 5]
max_num = max(numbers)
print(max_num)

5

In [65]:
#Finding the longest string in a list:
strings = ["apple", "banana", "orange", "kiwi"]
longest_string = max(strings, key=len)
print(longest_string)

banana

### min(iterable[, key, default]):

#### Returns the minimum element from the iterable.

In [66]:
#Finding the minimum value in a list
numbers = [1, 2, 3, 4, 5]
min_num = min(numbers)
print(min_num)

1

In [67]:
#Finding the minimum value in a dictionary:
scores = {"Alice": 85, "Bob": 90, "Charlie": 75}
min_score = min(scores.values())
print(min_score)

75

## Introduction to pandas: Series, DataFrame, data manipulation

## Pandas Overview

#### Pandas is a powerful Python library for data manipulation and analysis. It provides two primary data structures: Series and DataFrame.

### Installation: You can install Pandas using pip:
#### pip install pandas

### Series

#### Series is a one-dimensional labeled array capable of holding any data type. It is similar to a one-dimensional NumPy array but with additional functionality and a labeled index.

In [68]:
#Code Example:
import pandas as pd
s = [1,2,3,"Angel",4,5]
# Creating a Series from a Python list
S = pd.Series(s)
print(S)

0        1
1        2
2        3
3    Angel
4        4
5        5
dtype: object

#### DataFrame

#### DataFrame is a two-dimensional labeled data structure with columns of potentially different data types. It is similar to a spreadsheet or SQL table.

In [69]:
df = {'name':["Harriet", "Rashid", "Olalode"],
 'age':[59,45,34],
 'Location':["Boston", "Saskastchwan", "Colombus"]
 }


data = pd.DataFrame(df)
print(data)

      name  age      Location
0  Harriet   59        Boston
1   Rashid   45  Saskastchwan
2  Olalode   34      Colombus

In [70]:
#Code Example:
# Creating a DataFrame from a dictionary
data = {'Name': ['John', 'Alice', 'Bob'],
        'Age': [30, 25, 35],
        'City': ['New York', 'Paris', 'London']}
df = pd.DataFrame(data)
print(df)

    Name  Age      City
0   John   30  New York
1  Alice   25     Paris
2    Bob   35    London

## Data Manipulation

#### Indexing and Slicing: You can access and manipulate data in Series and DataFrame using indexing and slicing.

In [71]:
s = pd.Series([1, 2, 3, 4, 5])
# Accessing elements in a Series
print(s[3])

4

In [72]:
x = {'Name':["Harriet", "Rashid", "Olalode"],
     'Age': [30, 25, 35],
     'City': ['New York', 'Paris', 'London']}

df = pd.DataFrame(x)
print(df)

# Slicing a DataFrame
df[['Name']]  # Accessing a column

df[['Age']]

      Name  Age      City
0  Harriet   30  New York
1   Rashid   25     Paris
2  Olalode   35    London

   Age
0   30
1   25
2   35

### Data Combination

#### Data combination is the process of joining, merging or concatenating multiple pandas data structure into a single data structure.
#### The most common ways of combine dataframes are concatenation, joining and merge

### Concatenation

#### Using the `concat` function to combine two or more dataframes with the same columns either vertically or horizontally.

In [73]:
df_1 = pd.DataFrame({'A': [4, 2, 6,], 'B': ['m', 'n', 'o']})
df_2 = pd.DataFrame({'A': [45, 8, 9], 'B': ['x', 'y', 'z']})

In [74]:
df_1

   A  B
0  4  m
1  2  n
2  6  o

In [75]:
df_2

    A  B
0  45  x
1   8  y
2   9  z

In [76]:
# Vertical concatenation (row-wise)
vertical_com = pd.concat([df_1, df_2], axis=0, keys=["df_1", "df_2"])
vertical_com

         A  B
df_1 0   4  m
     1   2  n
     2   6  o
df_2 0  45  x
     1   8  y
     2   9  z

In [77]:
# Horizontal concatenation (column-wise)
horizontal_com = pd.concat([df_1, df_2], axis=1, keys=["df_1","df_2"])
horizontal_com

  df_1    df_2
     A  B    A  B
0    4  m   45  x
1    2  n    8  y
2    6  o    9  z

In [78]:
# Example with Weather Data
accra =pd.DataFrame({'Town':['Circle','Madina','East Legon'],
                    'Humidity':[32,29,34],
                    'Temperature':[28,30,25]})
kumasi =pd.DataFrame({'Town':['Kejetia','Amakom','Mantia'],
                    'Humidity':[27,39,36],
                    'Temperature':[30,26,24]})

In [79]:
df_3 = pd.concat([accra,kumasi], ignore_index=True)
df_3

         Town  Humidity  Temperature
0      Circle        32           28
1      Madina        29           30
2  East Legon        34           25
3     Kejetia        27           30
4      Amakom        39           26
5      Mantia        36           24

In [80]:
df_4 = pd.DataFrame({'Windspeed':[8,5,7,8,6,4,9,10,5]})
df_4

   Windspeed
0          8
1          5
2          7
3          8
4          6
5          4
6          9
7         10
8          5

In [81]:
pd.concat([df_3,df_4], ignore_index=True, axis=0)

          Town  Humidity  Temperature  Windspeed
0       Circle      32.0         28.0        NaN
1       Madina      29.0         30.0        NaN
2   East Legon      34.0         25.0        NaN
3      Kejetia      27.0         30.0        NaN
4       Amakom      39.0         26.0        NaN
5       Mantia      36.0         24.0        NaN
6          NaN       NaN          NaN        8.0
7          NaN       NaN          NaN        5.0
8          NaN       NaN          NaN        7.0
9          NaN       NaN          NaN        8.0
10         NaN       NaN          NaN        6.0
11         NaN       NaN          NaN        4.0
12         NaN       NaN          NaN        9.0
13         NaN       NaN          NaN       10.0
14         NaN       NaN          NaN        5.0

In [82]:
pd.concat([df_3,df_4], ignore_index=True, axis=1)

            0     1     2   3
0      Circle  32.0  28.0   8
1      Madina  29.0  30.0   5
2  East Legon  34.0  25.0   7
3     Kejetia  27.0  30.0   8
4      Amakom  39.0  26.0   6
5      Mantia  36.0  24.0   4
6         NaN   NaN   NaN   9
7         NaN   NaN   NaN  10
8         NaN   NaN   NaN   5